### ISSUE TITLE
Support for nesting

### ISSUE THREAD

**Issue by benguild** [insanoid/SwiftyJSONAccelerator#100]
I noticed this tool creates many files, even for structs with one or two properties that aren’t ever referenced outside of their parent.

It’d be great to consider nesting these at the highest level they’re required rather than always at the top level.

**Comment by insanoid** [comment]
The problem is that it is never clear by just structure what objects are going to be referenced directly and need a separate file and what can be inside the root-level object.

The best thing which is possible to have a single file option where everything is in one file with the file named based on the root-level object name that was entered. What are your thoughts on this @benguild?

**Comment by benguild** [comment]
It's easier to move things outward than inward, because if something needs to be referenced at a higher level... that scope would still cover both.

The structure of the JSON is in some cases the ideal structure for the Swift structs as well. If we're importing a single JSON file, then it'd be cool to convert it to a single Swift file with nested types.

**Comment by insanoid** [comment]
Do you mean something like this?

JSON: `{"address" : {"street": "221b Baker Street", "city": "London"}, "name": "Sherlock"}`

Result: `Person.swift`

```
struct Person {

 struct Address {
   let street: String
   let city: String
   ...
 }

let name: String
let address: Address
... 
}
```

If so, how do we handle double nested objects? for example, if `address` had another field called `attributes` which was an array of objects, would `Attributes` struct be nested inside `Person` or double-nested inside `Address`?

@benguild Sorry, my question might seem a bit ill-informed, I am interested in knowing more about how other people deal with these kinds of situations in their code-bases.

**Comment by benguild** [comment]
It’d be nested at the highest level necessary.
-- 
iPhoneから送信
