### ISSUE TITLE
"case private" should be created as: "case `private`"

### ISSUE THREAD

**Issue by moyoteg** [insanoid/SwiftyJSONAccelerator#118]
if a key is named "**private**" `case private` should be created as    ``case `private` ``.

**Comment by TheMadBug** [comment]
Having a go at this one now.

**Comment by TheMadBug** [comment]
Any chance this can get reviewed in Hacktober?
The code coverage technically went down 0.08% after my change, but I think that may have just been because I removed some code rather than adding untested stuff.
