### ISSUE TITLE
can we have a chance to set the name of a sub class?

### ISSUE THREAD

**Issue by ruixingchen** [insanoid/SwiftyJSONAccelerator#35]
when json file is big,we get a lot of files with a default name, these names will not always match, it will be better to have a chance to set the name of every sub class before we export it. that will be awesome.

**Comment by insanoid** [comment]
The whole point of the app is to have a well formatted JSON with key names that have to be variable names and would be a pain to generate/configure it by hand. You can always format the JSON you put in to have the names you need!

Also, the variable names are formatted in the Swift standard naming convention.
