### ISSUE TITLE
Merge Generated classes

### ISSUE THREAD

**Issue by muzamilhassan1987** [insanoid/SwiftyJSONAccelerator#36]
I want to know is there any solution i want to merge classes.
Like currently it create 2 3 classes but i want to merge them and use only one.
I can do in jsonaccelerator for objective C but i cant do it in swifty json

**Comment by insanoid** [comment]
I have given it some thought, I think models represents an individual object and should have a single file for that structure alone and if you need it in one file it is relatively easy to add text together.
I also checked JSONAccelerator (although the aim is not to be a clone and neither is this app affiliated with the franchise), they do not have that options.

Feel free to fork a version! It should be relatively easy to do, i believe that is the plus point of having the project open-source :)
