### ISSUE TITLE
Crash after generating class files

### ISSUE THREAD

**Issue by alexpersian** [insanoid/SwiftyJSONAccelerator#37]
Thanks for the great app!

Unfortunately I loaded it up today and it was consistently crashing after the model generation. It doesn't seem like a huge functionality issue since the class files are generated successfully, but it just crashes after that.

[Here's a crash report](https://gist.github.com/alexpersian/63ad8d2aec2c7883ef5d1533d13aa211). This is reproducible every time.

Steps to reproduce:
1. Load input area with valid JSON
2. Click 'generate' and select the directory.
3. Observe the crash. Class files will be in the directory though.

**Comment by insanoid** [comment]
Should no longer happen after 1.0.0, Done in https://github.com/insanoid/SwiftyJSONAccelerator/pull/31
Will go in Release 1.0.0.
