### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [insanoid/SwiftyJSONAccelerator#38]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by brytonmoeller** [comment]
Same

**Comment by olgusirman** [comment]
+1 for me

**Comment by SteveJKing** [comment]
+1 for me

**Comment by insanoid** [comment]
Thanks for letting me know! I was already updating the whole setup to a more flexible system prior to the release of Swift3, but got backtracked.

I am now updating the project for Swift 3, with better generation code, tests and making the extending to other libraries very easy etc. The release is version 1.0 and currently the UI part. You can follow https://github.com/insanoid/SwiftyJSONAccelerator/tree/issues/28-fix-code-base :)

**Comment by insanoid** [comment]
Version v1.0.0 is live now! Please let me know if it is all working well for you 🎉

**Comment by lfarah** [comment]
Thanks, @insanoid! 🎉 🎉🎉🎉🎉
