### ISSUE TITLE
NSCoding issue

### ISSUE THREAD

**Issue by farazhaider88** [insanoid/SwiftyJSONAccelerator#45]
In V->1.0.0 NSCoding code is not coming even NSCoding Check is enabled.
also class is not creating.

please look into this issue, ASAP. thanks

**Comment by insanoid** [comment]
Due to https://github.com/insanoid/SwiftyJSONAccelerator/issues/44.
Follow #47 should be fixed here.

**Comment by farazhaider88** [comment]
// MARK: NSCoding Protocol
    required public init(coder aDecoder: NSCoder) {
        self.productId = aDecoder.decodeObjectForKey(kBaseClassProductIdKey) as? String
        self.msg = aDecoder.decodeObjectForKey(kBaseClassMsgKey) as? String
        self.mappingId = aDecoder.decodeObjectForKey(kBaseClassMappingIdKey) as? String
        self.userGuid = aDecoder.decodeObjectForKey(kBaseClassUserGuidKey) as? String
        self.redirectModuleURL = aDecoder.decodeObjectForKey(kBaseClassRedirectModuleURLKey) as? String
        self.userTypeGuid = aDecoder.decodeObjectForKey(kBaseClassUserTypeGuidKey) as? String

```
}

public func encodeWithCoder(aCoder: NSCoder) {
    aCoder.encodeObject(productId, forKey: kBaseClassProductIdKey)
    aCoder.encodeObject(msg, forKey: kBaseClassMsgKey)
    aCoder.encodeObject(mappingId, forKey: kBaseClassMappingIdKey)
    aCoder.encodeObject(userGuid, forKey: kBaseClassUserGuidKey)
    aCoder.encodeObject(redirectModuleURL, forKey: kBaseClassRedirectModuleURLKey)
    aCoder.encodeObject(userTypeGuid, forKey: kBaseClassUserTypeGuidKey)

}
```

this part of NSCoding still not generating from this version. it was generating through older version.

**Comment by insanoid** [comment]
<img width="659" alt="screen shot 2016-11-17 at 12 42 45" src="https://cloud.githubusercontent.com/assets/193717/20388074/73689374-acc3-11e6-86e9-4444c2d2dcc8.png">

This is the Swift 3 version of NSCoding methods, which the app generates. You can download the older version at https://github.com/insanoid/SwiftyJSONAccelerator/releases/download/v0.0.6/SwiftyJSONAccelerator.zip which is for Swift 2.
