### ISSUE TITLE
1.4.0 crashed with macOS 10.12

### ISSUE THREAD

**Issue by HamGuy** [insanoid/SwiftyJSONAccelerator#53]
Here is the detail crash info:

> Exception Name: NSInvalidArgumentException
Description: Could not find a storyboard named 'Main' in bundle NSBundle </private/var/folders/p2/k10207q550b481p6jvwh9lpr0000gn/T/AppTranslocation/261BEBED-43F7-4CDC-8F1D-D458C283BD28/d/SwiftyJSONAccelerator.app> (loaded)
User Info: (null)
> 0   CoreFoundation                      0x00007fffa4ff252b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffb96cacad objc_exception_throw + 48
2   AppKit                              0x00007fffa3385485 -[NSStoryboard storyboardFileName] + 0
3   AppKit                              0x00007fffa2bbf744 NSApplicationMain + 399
4   SwiftyJSONAccelerator               0x0000000100c2fc39 main + 73
5   libdyld.dylib                       0x00007fffb9fa8255 start + 1

**Comment by insanoid** [comment]
@HamGuy
I have changed the app file, download again should work fine - https://github.com/insanoid/SwiftyJSONAccelerator/releases/download/v1.4.0/SwiftyJSONAccelerator.zip
