### ISSUE TITLE
Suggestion: Adding Entities Names?

### ISSUE THREAD

**Issue by farazhaider88** [insanoid/SwiftyJSONAccelerator#55]
Is there any way we can add the name of generated entities ? like having a preview of names of files appear and then we can change name regarding our requirement.

**Comment by insanoid** [comment]
Whenever I need something like this, I change the JSON key in the original JSON file before generated so my entities are generated with the correct file and variable names. I just change back the key in the JSON file in the enum. This is much simpler than allowing customisation while generation.

**Comment by farazhaider88** [comment]
any example for this ?

**Comment by insanoid** [comment]
If you have a JSON`{"value":{"name":"james", "id":123}}` and want the nested object to be called customer. Change the JSON to `{"customer":{"name":"james", "id":123}}`, it would generate `Customer.swift`

Go to main `.swift` model:
`
private struct SerializationKeys {
		static let customer = "customer"
`
Replace the string's value from `customer` to `value`
