### ISSUE TITLE
Error with Array JSON

### ISSUE THREAD

**Issue by n1rocket** [insanoid/SwiftyJSONAccelerator#58]
Hello, I try to do this example

```
{
  "pagination": {
    "total_pages": 1,
    "total_items": 1
  },
  "items": [
    {
      "id": "1",
      "name": "Area1"
    }
  ]
}
```

And in this line i have a problem

```
public required init(json: JSON) {
    if let items = json[SerializationKeys.items].array { items = items.map { Items(json: $0) } } //-------Cannot assign to value. 'items' is a 'let' constant
    pagination = Pagination(json: json[SerializationKeys.pagination])
  }
```

How can realize this struct?

Thanks!

**Comment by n1rocket** [comment]
I changed items to itemsA and work. Might when the app generate this structure will could change this. Thanks!

Sorry for my poor english

**Comment by insanoid** [comment]
Not sure what happened there, what was the library you selected, classname, company name etc.
