### ISSUE TITLE
Generics - Is possible to do this?

### ISSUE THREAD

**Issue by n1rocket** [insanoid/SwiftyJSONAccelerator#59]
Now i have an object "ListOfItems" for all list of my project, but I would like ListOfItems<Product> or ListOfItems<Person> with only one class. Could be do it with generics in SwiftyJSONAccelerator?

`{
  "pagination": {
    "total_pages": 1,
    "total_items": 2
  },
  "items": [
    {
      "id": "1",
      "name": "Section 1"
    },
    {
      "id": "2",
      "name": "Section 2"
    }
  ]
}`

Other:

`{
  "pagination": {
    "total_pages": 1,
    "total_items": 1
  },
  "items": [
    {
      "id": "1",
      "title": "Car 1"
      "price": 30000
    }
  ]
}`

Thanks, your work is awesome ;)

**Comment by insanoid** [comment]
Sorry, I don't think this is something that is not really in the scope of this project.
