### ISSUE TITLE
FeatureRequest: Add support for ObjectMapper's ImmutableMappable

### ISSUE THREAD

**Issue by pawartur** [insanoid/SwiftyJSONAccelerator#67]

**Comment by insanoid** [comment]
The protocol is still in beta and there might be breaking change in the API - https://github.com/Hearst-DD/ObjectMapper#immutablemappable-protocol-beta

Maybe will get to it at some point in the future.

**Comment by pawartur** [comment]
Thanks for responding :).

sob., 10 cze 2017 o 14:24 użytkownik Karthikeya Udupa KM <
notifications@github.com> napisał:
