### ISSUE TITLE
Can not generate class ESRI JSON route service 

### ISSUE THREAD

**Issue by fozoglu** [insanoid/SwiftyJSONAccelerator#69]
I am using ESRI route service I want to convert object from this (JSON [Link)](https://gist.github.com/fozoglu/bca7802e4b846c3f6b4e89a67abe3d7al) with SwiftyJSONAccelerator. But I have a problem one class. This class name "paths" (route array). I think this problem usage array in array. I tried to fix it, but it did not.

How can I fix. I'm glad you helped me.

[RouteResult.zip](https://github.com/insanoid/SwiftyJSONAccelerator/files/1065472/RouteResult.zip)

**Comment by insanoid** [comment]
@fozoglu theJSON link does not work, can you put the JSON file here?

**Comment by fozoglu** [comment]
@insanoid Thanks for feedback. I updated my question

**Comment by AnkleshwarDwivedi** [comment]
i am not able to install SwiftyJSONAccelerator  MAC Sierra .i clone it but its not working
