### ISSUE TITLE
Is it  possible to show the model code in another window without generating files?

### ISSUE THREAD

**Issue by ooyeah** [insanoid/SwiftyJSONAccelerator#73]
Usually, I use Xcode create a model file first, then copy the generated code to the file.

Although SwiftyJSONAccelerator can generate file to my project's folder, but I still need to "Add files to XX" in Xcode.

**Comment by insanoid** [comment]
Since it generates multiple files, showing it in the Ui is much more complex. I think it would be better to open the file and copy.
