### ISSUE TITLE
An error occurred while installing json (1.7.7),

### ISSUE THREAD

**Issue by 5SMNOONMS5** [insanoid/SwiftyJSONAccelerator#75]
![screen shot 2017-09-27 at 11 12 40 am](https://user-images.githubusercontent.com/8379901/30894191-d9322e92-a374-11e7-8670-1e534767826d.png)

This happened while type **make install**

**Comment by insanoid** [comment]
It's related to the ruby installation and not related to the project (and i do not have a solution unfortunately)
