### ISSUE TITLE
Can't install the app

### ISSUE THREAD

**Issue by sanchofox** [insanoid/SwiftyJSONAccelerator#78]
I downloaded the app only, but I can't install it.
When I try to install it, there is a message that says "[...] you should move it to the trash".
I also allowed on my Mac the installation of the apps from anywhere.

In addition, I run the following command line on terminal:

`spctl -a <my_path>/SwiftyJSONAccelerator.app `

but the return message is the following:

`CSSMERR_TP_CERT_REVOKED`

Please, help!

**Comment by dasoga** [comment]
+1

**Comment by iPhonig** [comment]
+1

**Comment by LivioGama** [comment]
I cloned the project using `git clone --recursive https://github.com/insanoid/SwiftyJSONAccelerator.git`
Then I set the development team to my own account. Then in Build phases I removed the last one Swift Lint and then I build the project to finally make it work. I archive the project and export to an app to have it in my Application folder.
