### ISSUE TITLE
cannot able to instal in 10.13.2 (high sierra)

### ISSUE THREAD

**Issue by farazhaider88** [insanoid/SwiftyJSONAccelerator#81]
i download the app after uncompressing , i clicked on the application but it given me error cannot be opened and move it to trash?

can any one let me know what is the issue?

**Comment by naveedahmad99** [comment]
I am facing the same issue

**Comment by ReetikaShukla** [comment]
yes, i am facing same issue. i didn't find any solution yet...

**Comment by farazhaider88** [comment]
open terminal type :      sudo spctl --master-disable
