### ISSUE TITLE
SwiftyJSONAccelerator.app can't open

### ISSUE THREAD

**Issue by jayeshthanki903** [insanoid/SwiftyJSONAccelerator#83]
When i download app from below link and open.
https://github.com/insanoid/SwiftyJSONAccelerator/releases/download/v1.4.0/SwiftyJSONAccelerator.zip

This will give me alert for "Move to Trash".

![screen shot 2018-02-06 at 2 57 13 pm](https://user-images.githubusercontent.com/8011134/35851533-4fcac9b0-0b4e-11e8-897e-bf5a3ed0e773.png)

**Comment by hiteshtrivedi** [comment]
I am getting the same issue. Any solution for it ?

**Comment by sami4064** [comment]
I am having same problem with app, and with make install I am getting:
`make: bundle: No such file or directory`

**Comment by hintoz** [comment]
Run in Terminal
`sudo xattr -rd com.apple.quarantine /Applications/SwiftyJSONAccelerator.app`

**Comment by naveedahmad99** [comment]
Still getting same error after running @hintoz command in terminal

**Comment by naveedahmad99** [comment]
Oh, first move SwiftyJSONAccelerator.app to Applications and then run the @hintoz  command to work...... Solved my problem. This issue should be closed now

**Comment by jayeshthanki903** [comment]
@hintoz,
Its work fine. Please close this issue.

**Comment by kgeorgek** [comment]
@hintoz Doesn't work in latest mac OS version.

**Comment by hintoz** [comment]
> @hintoz Doesn't work in latest mac OS version.

Can't check since the app crashes on Mac OS Mojave.
