### ISSUE TITLE
Will there be any updates in the future?

### ISSUE THREAD

**Issue by glennposadas** [insanoid/SwiftyJSONAccelerator#84]
Swift 4.2 is coming, or rather it already came. And there must be a further support or bug fixing.

For instance, I sometimes need the generated model class by SwiftJSONAccelerator to subclass the ```NSObject``` to support some stuff. And currently, I am experiencing crashes in  ```decodeBool```.

Crash:
```
self.first = aDecoder.decodeBool(forKey: SerializationKeys.first)
self.last = aDecoder.decodeBool(forKey: SerializationKeys.last)
```

Fix:
```
self.first = aDecoder.decodeObject(forKey: SerializationKeys.first) as? Bool
self.last = aDecoder.decodeObject(forKey: SerializationKeys.last) as? Bool
```

Thank you!

**Comment by DavidLari** [comment]
I don't think this is being supported anymore. I have switched to using https://quicktype.io/

**Comment by glennposadas** [comment]
Hey @DavidLari thank you so much for providing another solution to this. I tried it immediately, it's great! But does not support SwiftyJSON (maybe yet?) :D And does not put classes into separate files. Nevertheless, I would use it when SwiftyJSONAccelerator gets more outdated.

**Comment by insanoid** [comment]
Hello all, I haven't been able to update this repository due to time constraints, I will try to update it to latest Swift in the coming weeks!

**Comment by insanoid** [comment]
Meanwhile, any pull requests on the dev branch are welcome!

**Comment by glennposadas** [comment]
Thank you, @insanoid . Do you still use SwiftyJSON though in your production projects? Just wondering.

**Comment by glennposadas** [comment]
Also, this does not work anymore on Mojave.

**Comment by insanoid** [comment]
@glennposadas Thanks for letting me know. I will be working on a new version with support for Swift 4 (without SwiftyJSON) among other upgrades to existing features.

Regarding using SwiftyJSON in production, I have moved away from app development for a while (hence the reason for not having the app up to date), but we have some older swift code that still has SwiftyJSON but in the future, I am going to move away from it.

**Comment by insanoid** [comment]
Now fixed for Mojave (but only Swift 3 code is being generated) - This will be the last legacy version support.
