### ISSUE TITLE
SwiftyJSONAccelerator crashes on launch under Mojave 10.14

### ISSUE THREAD

**Issue by musbaalbaki** [insanoid/SwiftyJSONAccelerator#86]

**Comment by 4kr4m** [comment]
Facing the same issue as well on Mojave 10.14 
<img width="532" alt="screen shot 2018-10-03 at 9 34 35 am" src="https://user-images.githubusercontent.com/1760927/46393876-b02ca780-c6ef-11e8-9bf9-44a752c1ca30.png">

**Comment by musbaalbaki** [comment]
I guess it is a code signing issue

**Comment by 4kr4m** [comment]
yeah that seems right:
Exception Type:        EXC_CRASH (Code Signature Invalid)

**Comment by musbaalbaki** [comment]
@4kr4m I found out if you use the version just before the last one (v1.3.0), it will actually work on Mojave.

https://github.com/insanoid/SwiftyJSONAccelerator/releases/download/v1.3.0/SwiftyJSONAccelerator.zip

**Comment by 4kr4m** [comment]
@musbaalbaki Works like charm, Thank you

**Comment by naveedahmad99** [comment]
@musbaalbaki solution worked in Mojave. Thanks man

**Comment by insanoid** [comment]
Now fixed for Mojave (but only Swift 3 code is being generated) - This will be the last legacy version support.
