### ISSUE TITLE
Not work macos mojave!

### ISSUE THREAD

**Issue by italoBianchini** [insanoid/SwiftyJSONAccelerator#87]

**Comment by gabrielvieira** [comment]
you already try this - https://github.com/insanoid/SwiftyJSONAccelerator/issues/83 ?

sudo xattr -rd com.apple.quarantine /Applications/SwiftyJSONAccelerator.app

**Comment by tiendaik** [comment]
@gabrielvieira it's not working

**Comment by gabrielvieira** [comment]
@tiendaik Clone repo and run in your xcode, will works

**Comment by musbaalbaki** [comment]
https://github.com/insanoid/SwiftyJSONAccelerator/issues/86

**Comment by dasoga** [comment]
This worked 
https://github.com/insanoid/SwiftyJSONAccelerator/issues/86#issuecomment-426922523

**Comment by insanoid** [comment]
Now fixed for Mojave (but only Swift 3 code is being generated) - This will be the last legacy version support.
