### ISSUE TITLE
not able to download

### ISSUE THREAD

**Issue by mohsinalimat** [insanoid/SwiftyJSONAccelerator#92]
Hello,

not able to download from below link

https://github.com/insanoid/SwiftyJSONAccelerator/releases/download/v1.5.0/SwiftyJSONAccelerator.zip

**Comment by insanoid** [comment]
https://github.com/insanoid/SwiftyJSONAccelerator/releases/download/v1.5.0/SwiftyJSONAccelerator.app.zip

Link was broken, now it's fixed.
