### ISSUE TITLE
Add init function for class generation

### ISSUE THREAD

**Issue by insanoid** [insanoid/SwiftyJSONAccelerator#97]
When the construct type is a `class` the user should be able to request for an `init` function for the class that takes all the attributes declared in the class as parameters and sets them to their corresponding attribute in the class.

- An additional checkbox should be provided in the UI (enabled only when the construct is of type `class`).
- The CLI should also provide a similar option.

For Example:

**JSON**:  `{"var1": "randomstring", "var2": "anotherrandomstring" }`
**Construct Type:** `class`
**Need Init Function**: `true`
**Variables as Optionals**: `true`

**Result**
```
init(var1: String?, var2: String?) {
 self.var1 = var1
 self.var2 = var2
}
```

**Comment by RomanPodymov** [comment]
Hello @insanoid 
Could you please provide more detailed description for this feature?

**Comment by insanoid** [comment]
@RomanPodymov I have updated the comment, hopefully it makes more sense now.
